### ISSUE TITLE
Addition to cdnjs

### ISSUE THREAD

**Issue by vagdwd** [Pikaday/Pikaday#167]
Can you add this library to a public cdn like cdnjs.com? It will be beneficial for community.

**Comment by wojciechczerniak** [comment]
Most of the CDNs can load the package from NPM now.

Requested CDNJS is here: https://cdnjs.com/libraries/pikaday
Another one from JSDelivr: https://www.jsdelivr.com/package/npm/pikaday

I've added the CDN to our Readme, thanks for the idea!
