### ISSUE TITLE
Show days of next month

### ISSUE THREAD

**Issue by ITspirit** [Pikaday/Pikaday#176]
Is it possible at the moment to show the dates of the next Month?

For example - i look at the "September 2014" - at the end it would be great that free "td" will be filled with the dates of the next month (with another color).

How can i do this at the moment or if not - is it possible to expect this feature in the future?

**Comment by jonathansimmons** [comment]
It would be nice to have this as an option. 

@eadmundo any interest in updating your branch for the latest release?

**Comment by eadmundo** [comment]
Yes absolutely - I'll have a look in the next couple of days

**Comment by eadmundo** [comment]
I've done a new PR for this, since I no longer have access to the repo linked above:

https://github.com/dbushell/Pikaday/pull/381

**Comment by wojciechczerniak** [comment]
Merged in #381
