### ISSUE TITLE
Feature request: parse and format hooks

### ISSUE THREAD

**Issue by HowlingEverett** [Pikaday/Pikaday#277]
Pikaday + Moment.js is great, but moment.js adds an additional 12.5kB gzipped to the page load which is wasted bytes if the only place in the browser you're using date parsing/formatting is specifically for dealing with datepickers.

In these cases a lightweight, less-flexible date parsing and formatting function would work just as well for a fraction of the bytes. In my current application, I'm manually formatting and setting the parsed value in Pikaday's `onSelect` callback, however this callback fires _after_ the original unformatted value is set back to the field. This has a number of drawbacks, the main one being that I am hooked into the onchange event on said field, which then fires with an invalid, unformatted value.

I would love to see an onFormat callback that works a little like this:

```
new Pikaday({
  field: document.selectElementById('myField'),
  format: function (date) {
     var formattedValue;
     // Do some formatting here...
     return formattedValue;
  }, 
  parse: function (dateString) {
    // Do some custom parsing
    return parsedDate;
  }
});
```

You could then, if you chose, use moment.js like any other formatter, by passing the moment constructor to parse and moment.format to format.

**Comment by gaydenko** [comment]
:+1:  Yes, `moment` as the only formatter is really unhandy. And, by the way, I would separate dealing with parsing and formatter. At my use case I don't need parser at all. Probably, the team will be more disposed to resolve the issue divided into two pars step by step :)

**Comment by Deraen** [comment]
:+1:

**Comment by mb21** [comment]
Agreed, moment.js is becoming larger and larger...

As it stands, I went for a mini-moment.js-shim for my locale `DD.MM.YYYY`, which you can adapt. Unfortunately, it turned out larger than expected, as pikaday tries to use moment.js functionality whenever possible. Remember to execute this before you load pikaday.js

    //moment.js shim
    var moment = function(value, format, formatStrict) {
      var date;
      if (typeof value === 'string') {
        date = new Date( format === 'DD.MM.YYYY'
                         ? value.split('.').reverse().join('-')
                         : Date.parse(value)
                       );
      } else if (Object.prototype.toString.call(value) === '[object Date]') {
        date = value;
      } else {
        throw 'value was neither a string nor a date'
      }
      var adjustDate = function(sign, days, unit) {
        if (unit === 'days') {
          var difference = parseInt(days)*24*60*60*1000;
          date = new Date( sign === 'add'
                           ? date.valueOf() + difference
                           : date.valueOf() - difference
                         );
          return momentObj;
        } else {
          throw "only days supported"
        }
      };

      var momentObj = {
        _isAMomentObject: true
      , add: adjustDate.bind(this, 'add')
      , format: function(f) {
          if (f === 'DD.MM.YYYY') {
            var mm = date.getMonth() + 1; // getMonth() is zero-based
            var dd = date.getDate();
            return [ (dd>9 ? '' : '0') + dd
                   , (mm>9 ? '' : '0') + mm
                   , date.getFullYear()
                   ].join('.');
          } else {
            return date.toDateString();
          }
        }
      , isValid: function() {
          return date && !isNaN(date);
        }
      , subtract: adjustDate.bind(this, 'subtract')
      , toDate: function() {
          return date;
        }
      };
      return momentObj;
    };
    moment.isMoment = function(obj) {
      return obj != null && obj._isAMomentObject != null;
    };

**Comment by wojciechczerniak** [comment]
`toString` and `parse` methods were introduced in v1.6.0
