### ISSUE TITLE
defaultDate, setdefaultdate setting to moment().toDate() incorrect

### ISSUE THREAD

**Issue by anjalisingh** [Pikaday/Pikaday#280]
configurations:

defaultDate the initial date to view when first opened
setDefaultDate make the defaultDate the initial selected value

setting the following parameters for picker:

{
            field: document.getElementById('datepicker1'),
            defaultDate: moment().toDate(),    //14 Mar 2015
            format: 'Do MMMM YYYY',
}

date shown: 1 Jan 2016

**Comment by HorizonShadow** [comment]
Use

````
{
field: document.getElementById('datepicker1'),
defaultDate: moment().toDate(), //14 Mar 2015
setDefaultDate: true,
format: 'Do MMMM YYYY',
}
````

**Comment by wojciechczerniak** [comment]
Looks like the issue was solved. Thanks @HorizonShadow

**Comment by kevinsar** [comment]
did this bug come back? I've tried:
{
      defaultDate: moment('Nov 1, 2019').format('MMMM DD, YYYY'),
      setDefaultDate: true,
}

And when I click into the input field, the calendar opens up to today's current date.
