### ISSUE TITLE
How do you set locale?

### ISSUE THREAD

**Issue by azamat-sharapov** [Pikaday/Pikaday#299]
When using webpack or browserify, how do you set locale for moment.js?

**Comment by VisualBean** [comment]
You should really ask this on StackOverflow or over at moments github..

**Comment by azamat-sharapov** [comment]
@VisualBean I know how to do it for moment.js, but when using webpack, pikaday `require`s moment.js by itself and I can't change locale for it. I tried `getMoment().locale('ru')` in all events of pikaday, it doesn't have effect. I tried to hardcode changing locale in pikaday.js from node_modules directory, it worked, but that's not the way to do it.

I think this is issue for pikaday, not moment. Perhaps instructions from readme missing, I don't know.

**Comment by nverba** [comment]
I've found this using Browserify. If you delete pikaday's moment folder from it's node_modules directory, you can then require moment in your own script and the locale will work. It's still not ideal though.

```JS
var moment = require('moment');
require('moment/locale/de');
```

**Comment by mateatslc** [comment]
@azamat-sharapov here: http://stackoverflow.com/a/25426019

**Comment by azamat-sharapov** [comment]
@mateatslc thanks, but my issue is not about that.

**Comment by mateatslc** [comment]
this might help: https://github.com/dbushell/Pikaday/issues/67

"... moment should have its locale set before instantiating Pikaday and if moment's locale changed this does not automatically change Pikaday's format."

**Comment by wojciechczerniak** [comment]
Question was answered. I can close this issue.
