### ISSUE TITLE
iOS Safari " Invalid CSS property declaration at: * "

### ISSUE THREAD

**Issue by RedoAoura** [Pikaday/Pikaday#306]
Hey guys,

I get this error on iOS Safari browser <code>Invalid CSS property declaration at: _</code> 
Caused by CSS-HACK on pikaday.css file, lines 94, 95, 107 and 114. there is a "_ start" before the css property. 

I guess reason of this hack is for IE6 and 7. But can we get rid of this hack?

Thanks!

**Comment by DolphRoger** [comment]
+1 for this. Note that using ugly star-hack randomly breaks css compressors like CSSMin. It cost me a while to find out that it was pikaday causing this. Please do not use CSS-Hacks.

**Comment by eliseumds** [comment]
@DolphRoger or create different CSS files and let the developers decide what to include.

@RedoAoura https://github.com/jakubpawlowicz/clean-css could help you there.

**Comment by memoht** [comment]
+1 for this. Safari for OS X doesn't like these either.

**Comment by wojciechczerniak** [comment]
We're dropping IE support and this issue was resolved in #430
