### ISSUE TITLE
Can't use defaultDate, and setDefaultDate in IE8

### ISSUE THREAD

**Issue by raymonschouwenaar** [Pikaday/Pikaday#315]
For building a application I wanted to use the defaultDate and setDefaultDate. But in IE8 the date is not being selected and also not filled in the input field. With that problem I wanted to set the yearRange to a year of 100 years ago and 15 years ago. But that didn't work! 

Is there a solution for this?

**Comment by wojciechczerniak** [comment]
We're going to drop support for older IE versions. Sorry. I'm closing the issue.
