### ISSUE TITLE
Very serious bug found (fix provided)

### ISSUE THREAD

**Issue by ghost** [Pikaday/Pikaday#374]
We found a very serious bug in pikaday.

When pikaday is used on a touch-enabled device, but used with mouse - it's absolutely not possible to click on dates in datepicker. A lot of customers with touch-enabled laptops (like Carbon X1) repored us this problem.

This happens because of the following line:

```
addEvent(self.el, 'ontouchend' in document ? 'touchend' : 'mousedown', self._onMouseDown, true);
```

'ontouchend' in document will return true, but as it used with mouse, you cannot select a date with mouse...

We fixed the issue by registering both events at the same time:

```
addEvent(self.el, 'mousedown', self._onMouseDown, true);
addEvent(self.el, 'touchend', self._onMouseDown, true);
```

We also tried to fix the issue by registering only one event (mousedown or touchend), but we wasn't successful at this as we always found cases when some device didn't work.

We tested the fix on multiple devices (iPad, iPhone, Android, Windows...) without any issues.

**Comment by kaib84** [comment]
I also found another issue #276 which reported a similar problem.

**Comment by nathancahill** [comment]
Can you submit a PR?

**Comment by gaastonsr** [comment]
Is this resolved?

**Comment by szwacz** [comment]
I believe so.
