### ISSUE TITLE
Weeknumbers are off when 2016 starts

### ISSUE THREAD

**Issue by andersdp** [Pikaday/Pikaday#388]
In europe (Denmark where I'm located) we use weeknumbers a lot to manage our schedules/holidays/work and so on.

This year the last week is 53 which spans from monday 28.dec to sunday 03.jan which means that weeknumber 1 in 2016 starts on monday 04.jan. However pikaday actually shows the date range 28.dec to 03.jan as both week 53 and 1:
![skaermbillede 2015-08-20 kl 11 24 09](https://cloud.githubusercontent.com/assets/4325383/9380082/20f192d6-472e-11e5-8962-ac174760e0de.png) ![skaermbillede 2015-08-20 kl 11 24 23](https://cloud.githubusercontent.com/assets/4325383/9380085/2d2c813c-472e-11e5-8384-3fdfbca4391b.png)

The ISO definiton of weeknumbering can be found here: https://en.wikipedia.org/wiki/Week#Week_numbering

**Comment by snowyseal** [comment]
weeknumber.net suggest this to calculate ISOweek numbers. Replace renderWeek() function with:
 
renderWeek = function (d, m, y) {
        // Lifted from http://weeknumber.net/how-to/javascript
        //var date = new Date(this.getTime());
        var date = new Date(y, m, d);
        date.setHours(0, 0, 0, 0);
        // Thursday in current week decides the year.
        date.setDate(date.getDate() + 3 - (date.getDay() + 6) % 7);
       // January 4 is always in week 1.
       var week1 = new Date(date.getFullYear(), 0, 4);
       // Adjust to Thursday in week 1 and count number of weeks from date to week1.
       var weekNum = 1 + Math.round(((date.getTime() - week1.getTime()) / 86400000 - 3 + (week1.getDay() + 6) % 7) / 7);
       return '<td class="pika-week">' + weekNum + '</td>';
    },

Very lightly tested...

SS

**Comment by mcroba** [comment]
Hello,

Could you please add an option to use the `moment(new Date(y, m, d)).isoWeek()` in order to have the right ISO week number?

In 2016, all weeks in Pikaday calendar would be wrong accordingly to ISO week (http://www.epochconverter.com/date-and-time/weeknumbers-by-year.php?year=2016):

4 - 10 January should be week 1 not 2
11 - 17 should be 2 not 3
... etc.

Thanks in advance for the fix.

Best Regards,
Sylvain

**Comment by jlami** [comment]
Can this be published as 1.8.1?

**Comment by wojciechczerniak** [comment]
@jlami Sorry but too many changes were merged already that may be a breaking change.
