### ISSUE TITLE
[BUG] MinDate does not affect default month displayed

### ISSUE THREAD

**Issue by scspijker** [Pikaday/Pikaday#425]
May 2015 ends on a Sunday. Now disable weekends and set your date to May 30th 2015 (Saturday). Automatically, June 2015 will show instead of the current month (May) when opening the picker for the first time. This is desired because else a user would be presented with a month without options.

Now here is the problem: set your date to May 29th 2015, but set the minimum date for the date picker to May 30th 2015. Refresh the page and open the calender. It will still open on May 2015, because it ignores the minimum date in determining the first month where options are available. This presents the user with a useless month.

This is not an edge case, for me it is very valid because I need my datepicker to allows picks from tomorrow and on. This means that on that Friday, minimum date is Saturday (tomorrow) but weekends are disabled, and thus June has the first eligible option.

Current I'm working around this by setting defaultDate to the first day in the next month.

**Comment by ryoia** [comment]
I am also experiencing this issue since we need to set the minDate as the next day.
