### ISSUE TITLE
New release for latest merged PRs

### ISSUE THREAD

**Issue by dennisausbremen** [Pikaday/Pikaday#453]
Hello,
could you please create a new release for the latest PRs that have been merged?
Namely because of the "Strict Date Parsing" PR.

**Comment by laurentChin** [comment]
+1

**Comment by listepo** [comment]
+1

**Comment by spirosikmd** [comment]
+1

**Comment by rey-awesense** [comment]
+1

**Comment by wojciechczerniak** [comment]
Done a long time ago.
