### ISSUE TITLE
format with moment.js is buggy

### ISSUE THREAD

**Issue by dit-j** [Pikaday/Pikaday#463]
according to Pikaday docs: "For advanced formatting load Moment.js prior to Pikaday".

moment-with-locales.js was loaded and default locale was set using "moment().locale('de')". But this has no effect. Pikaday still formating the date by using 'en'.

**Comment by wachunei** [comment]
I guess you should use `moment.locale('de')`, which is a global option to set localization. When you use `moment().locale('de')` you are only affecting that `moment()` object (notice the `()`)

**Comment by wojciechczerniak** [comment]
Question was answered. I can close this issue. Thanks @wachunei
