### ISSUE TITLE
Some confuse about date picker range.

### ISSUE THREAD

**Issue by poppinlp** [Pikaday/Pikaday#471]
In you [demo page](http://dbushell.github.io/Pikaday/), the setting for max-date is `maxDate: new Date(2020, 12, 31)`. But if i input a later date such as 'Sun Jan 31 2022', it will auto change to 'Sun Jan 31 2021'. So what's that date and why it's not maxDate from setting? And month picker won't handle click action until change to date inside setting range.

**Comment by rglyall** [comment]
The month argument in the `Date` constructor is zero-based, so you'll need to pass in `maxDate: new `Date(2020, 11, 31)` if you want to get the correct date. Alternatively, if that feels a bit alien, you could pass a string instead - for example, `new Date('2020-12-31')`. Both would result in `Thu Dec 31 2020 00:00:00 GMT+0000 (GMT)` as the `maxDate`.

**Comment by wojciechczerniak** [comment]
Question was answered. I can close this issue now. Thanks @robertlyall

**Comment by poppinlp** [comment]
Sry i forgot to close this issue. Thanks. @wojciechczerniak  @robertlyall
