### ISSUE TITLE
Feature request: Use month/day names from moment.js

### ISSUE THREAD

**Issue by vanderlee** [Pikaday/Pikaday#472]
If Moment.js is available, it would be nice if Pikaday automatically used the month/day names of moment.js instead of requiring separate translations.

**Comment by demogorgorn** [comment]
+1

**Comment by vanderlee** [comment]
For what it's worth, you can set up most of the locale from Moment in Javascript:

	moment.locale('nl');

	var pikadayLocale = {
		previousMonth: 'Previous Month',
		nextMonth: 'Next Month',
		months: moment.months(),
		weekdays: moment.weekdays(),
		weekdaysShort: moment.weekdaysShort()
	};

**Moment.js** does not have equivalents for `previousMonth` and `nextMonth`

**Comment by demogorgorn** [comment]
Thanks!

**Comment by wojciechczerniak** [comment]
Great solution @vanderlee! Solved.
