### ISSUE TITLE
Releasing version 1.4.1

### ISSUE THREAD

**Issue by Patsy-issa** [Pikaday/Pikaday#474]
The currently available release does not include the latest changes that added `strictFormat`

**Comment by dennisausbremen** [comment]
+1 
see also:
#453

**Comment by owenmead** [comment]
Will also release 1.4.1 timepicker branch once this has been released.

**Comment by dennisausbremen** [comment]
@dbushell: Are there still things that need to be merged for 1.4.1? Would be really great getting rid of all the workarounds.

**Comment by dennisausbremen** [comment]
*bump*

**Comment by gibson** [comment]
bump it please
you are alive?

**Comment by wojciechczerniak** [comment]
Changes were released some time ago.
