### ISSUE TITLE
Unselect bug

### ISSUE THREAD

**Issue by jdaudier** [Pikaday/Pikaday#475]
I need some guidance on an issue I'm running into.  I'm trying to **unselect** a certain date after a user presses the `Cancel` button.

**I used this code to clear the selected date:**
1. `startDatePicker.setMinDate(today);`
2. `startDatePicker.setDate(today, true);`
3. `.$('.is-selected').removeClass('is-selected');`

This works fine but the bug I'm running into is if I go forward a month and go back to this month, the `is-selected` class is no longer removed on today's date.  

**It's almost as if there are 2 instances of this month.**

Any guidance or tip will be greatly appreciated!

![cancel-bug](https://cloud.githubusercontent.com/assets/1666031/12434245/945e8a2c-bed3-11e5-967e-e7362e8c58f5.gif)

**Comment by entonbiba** [comment]
@jdaudier you can do `picker.setDate(null)`.

**Comment by wojciechczerniak** [comment]
Answered. Thanks @entonbiba
