### ISSUE TITLE
Input blur event triggered on IE

### ISSUE THREAD

**Issue by pedroabreu** [Pikaday/Pikaday#481]
I've hit an interesting (or maybe dumb) issue on IE. So, I've defined a div as the field to trigger the calendar and everything works fine on Chrome and FF but not on IE (surprise, surprise). When I click the div to open the calendar, it triggers the inputBlur but only on IE

From what I've investigated the issue lies on the _onInputBlur (Line 509) event that is triggered on IE and forces the calendar to hide again. I've been trying to cancel the blur event but I've not being successful in that (hence this issue)

On a side note why property names like _c , _v, _d ? I'm sure it has a reason but it's just not that obvious (At least for me)

Does anyone have any idea on how to workaround this ?

**Comment by pedroabreu** [comment]
My workaround for this: 
On my onOpen callback I remove the _onInputBlur event

    elem[0].removeEventListener('blur', daterangePicker._onInputBlur, false);

It's definitely not the ideal solution but it matches my requirements, although I will continue to investigate because now I'm curious to understand why does only IE trigger this event

**Comment by DylanFM** [comment]
I too am a bit confused by `_c` etc. Trying to debug a little UX issue and it seems to be related to `_c`. Descriptive names and or comments would be good here.

**Comment by spsaucier** [comment]
In Chrome 62 (non-incognito), `_onInputBlur` is being triggered in my application after the opening click as well. It works correctly in incognito without extensions, but even if I disable all extensions in normal mode, a `blur` appears to be triggered, though the element appears to keep focus. `element[0].removeEventListener("blur", scope.pikaday._onInputBlur);` in the `onOpen` function doesn't seem to be removing the event listener, either.
