### ISSUE TITLE
Time as well as date

### ISSUE THREAD

**Issue by LiamDawe** [Pikaday/Pikaday#487]
Just curious, is there/will there ever be a way to include time as well?

**Comment by owenmead** [comment]
https://github.com/owenmead/Pikaday

**Comment by owenmead** [comment]
Most people don't need time, so a separate fork is maintained.

**Comment by NaughtySquid** [comment]
Thanks, using it now works great!

**Comment by wojciechczerniak** [comment]
Duplicate of #191
