### ISSUE TITLE
[Solution]: Next Previous month not working/closing datepicker on mobile browsers

### ISSUE THREAD

**Issue by davorpeic** [Pikaday/Pikaday#508]
I was having issues on Mobile Safari/Mobile Chrome where was impossible to change dates because datepicker would close immediately. 

I traced the issue to case when I'm using Pikaday in combo with FastClick plugin, so the solution is to add class `needsclick` to parent pikaday div and on the buttons, I did this inside the pickaday.js.

More about needsclick: [https://github.com/ftlabs/fastclick#ignore-certain-elements-with-needsclick](https://github.com/ftlabs/fastclick#ignore-certain-elements-with-needsclick)

davor

**Comment by wojciechczerniak** [comment]
Not a problem with Pikaday but thanks for the solution.  I'm archiving this issue.
