### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by rikkert** [Pikaday/Pikaday#51]
Mocha unit tests should at least be added for:
- [ ] Plain version
- [ ] AMD version
- [ ] jQuery plugin
- [ ] With moment.js
- [ ] Bugs that have been closed to prevent regressions
- [ ] Every exposed / documented method

Would be great to have them run in [testling-ci](https://ci.testling.com/).

**Comment by DanielRuf** [comment]
Any updates? Currently there is no active CI.

**Comment by rikkert** [comment]
True, you know of any active alternative?

**Comment by DanielRuf** [comment]
We often use TravisCI and CircleCI with Jest, Puppeteer and Browserstack.

**Comment by rikkert** [comment]
That sounds great, any change you could take a stab at this?
