### ISSUE TITLE
week number

### ISSUE THREAD

**Issue by seeley60** [Pikaday/Pikaday#512]
Here in Switzerland if I display week number I have "18" for today (2016.04.29) but moment display "17" for the same day.

For us "17" is correct.

**Comment by andrei-sheina** [comment]
Have the exact same issue. Option showWeekNumber show weeknumber + 1

**Comment by Electrofenster** [comment]
@andrei-sheina how do you solved it?

**Comment by seeley60** [comment]
I follow this :

https://github.com/dbushell/Pikaday/pull/443/commits/37478ffd8e6117fb3b81c74d1ee87c38e89252e4

and it works :-)

Jacques Bourquin

Chemin de la Maison Blanche 33
CH-2533 Evilard


Le 4 mai 2016 à 09:53:34, Lars (notifications@github.com) a écrit:

@andrei-sheina how do you solved it?

**Comment by wojciechczerniak** [comment]
Duplicate of #388
