### ISSUE TITLE
do we need to call destroy method  in react - componentWillUnmount

### ISSUE THREAD

**Issue by craigcosmo** [Pikaday/Pikaday#517]
do we need to call destroy method  in react - componentWillUnmount ?

**Comment by tomasswood** [comment]
Yes. You should intialise in `componentDidMount` and destroy your date pickers in `componentWillUnmount`.

**Comment by jackson-sandland** [comment]
How do you destroy? `component.destroy()`?

**Comment by tomasswood** [comment]
It's been a while since I worked on that project, but I believe I just assigned the date picker to `this.pickerName` in the component

**Comment by wojciechczerniak** [comment]
The question was answered. I'm closing this issue. Thanks @tomasswood
