### ISSUE TITLE
toLocaleDateString as default formatter

### ISSUE THREAD

**Issue by khades** [Pikaday/Pikaday#519]
is it possible to use toLocaleDateString() function to localise pikaday interface? moment.js is kinda heavy on size

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString

**Comment by DAN900** [comment]
This would be very welcome!

**Comment by mb21** [comment]
Agreed, moment.js is becoming larger and larger and `toLocaleDateString` and `fromLocaleDateString` callbacks would really be a nice solution.

As it stands, I went for a mini-moment.js-shim for my locale `DD.MM.YYYY`, which you can adapt. Unfortunately, it turned out larger than expected, as pikaday tries to use moment.js functionality whenever possible. Remember to execute this before you load pikaday.js

    //moment.js shim
    var moment = function(value, format, formatStrict) {
      var date;
      if (typeof value === 'string') {
        date = new Date( format === 'DD.MM.YYYY'
                         ? value.split('.').reverse().join('-')
                         : Date.parse(value)
                       );
      } else if (Object.prototype.toString.call(value) === '[object Date]') {
        date = value;
      } else {
        throw 'value was neither a string nor a date'
      }
      var adjustDate = function(sign, days, unit) {
        if (unit === 'days') {
          var difference = parseInt(days)*24*60*60*1000;
          date = new Date( sign === 'add'
                           ? date.valueOf() + difference
                           : date.valueOf() - difference
                         );
          return momentObj;
        } else {
          throw "only days supported"
        }
      };

      var momentObj = {
        _isAMomentObject: true
      , add: adjustDate.bind(this, 'add')
      , format: function(f) {
          if (f === 'DD.MM.YYYY') {
            var mm = date.getMonth() + 1; // getMonth() is zero-based
            var dd = date.getDate();
            return [ (dd>9 ? '' : '0') + dd
                   , (mm>9 ? '' : '0') + mm
                   , date.getFullYear()
                   ].join('.');
          } else {
            return date.toDateString();
          }
        }
      , isValid: function() {
          return date && !isNaN(date);
        }
      , subtract: adjustDate.bind(this, 'subtract')
      , toDate: function() {
          return date;
        }
      };
      return momentObj;
    };
    moment.isMoment = function(obj) {
      return obj != null && obj._isAMomentObject != null;
    };

**Comment by mb21** [comment]
see also #277

**Comment by El4a** [comment]
is there any news on this feature? I love the pikaday lib (fits almost all my needs) except the parsing. Driving me crazy

**Comment by wojciechczerniak** [comment]
`toString` and `parse` methods were introduced in v1.6.0
