### ISSUE TITLE
Can we have a new release?

### ISSUE THREAD

**Issue by jeantimex** [Pikaday/Pikaday#532]
Since there are so many nice fix after v1.4.0.

**Comment by masimies** [comment]
Yes, greetings from Finland,
This is a greate datepicker, but i don't get it, why there is a need of over 4000-rows code with moment.js for get date format in other regions than US.
I just get rid of bootstrap and jquery, and saved over 16000-readable rows from my web-portal.

**Comment by urbany** [comment]
Any idea when we'll get a new release?
Awesome plugin :)

**Comment by wojciechczerniak** [comment]
Pikaday was released a few times since 1.4.0. We can close this issue.
