### ISSUE TITLE
Pikaday is not defined

### ISSUE THREAD

**Issue by zolotykh** [Pikaday/Pikaday#544]
Time to time I have that: _Uncaught ReferenceError: Pikaday is not defined_

`Chrome: Version 53.0.2764.0 canary (64-bit)`

**Comment by BMalaichik** [comment]
@zolotykh Do you use native js\jquery or any other framework(angular 1\2, react) ?
maybe, you try to initialize pickaday before script was loaded in index.html

**Comment by zolotykh** [comment]
@BMalaichik в том и дело, что все выглядит асинхронно, но по факту синхронно и по порядку.
Сегодня заметил схожее поведение при использовании nanoScroller, теперь думаю может дело в браузере.

**Comment by AnimalInstinct** [comment]
r=document.createElement("script");
r.type="text/javascript",
r.async=!0,
r.src="https://cdnjs.cloudflare.com/ajax/libs/pikaday/1.4.0/pikaday.min.js",
document.head.appendChild(r);
var picker = new Pikaday({ field: document.getElementById('datepicker') });

Doesn't work, anybody know why? Pikaday is not defined :(

**Comment by zolotykh** [comment]
@AnimalInstinct 
`
var picker;
var r=document.createElement("script");
r.type="text/javascript";
r.async=false;
r.onload = function(){
    picker = new Pikaday({ field: document.getElementById('datepicker') });
};
r.src="https://cdnjs.cloudflare.com/ajax/libs/pikaday/1.4.0/pikaday.min.js";
document.head.appendChild(r);
`

**Comment by BMalaichik** [comment]
@zolotykh попробуй инициализировать во время window.onload() эвента

**Comment by wojciechczerniak** [comment]
Looks like it's solved with `onload` function.
