### ISSUE TITLE
Why are the PR's not being used?

### ISSUE THREAD

**Issue by tsteuwer** [Pikaday/Pikaday#556]
@dbushell I'm seeing a ton that are well worth their value. Why isn't this getting addressed?

**Comment by DarkMarmot** [comment]
This project seems to be languishing -- which is really sad because it's a great little library. Maybe someone should try to become the new canonical fork?

**Comment by wojciechczerniak** [comment]
We will do our best to address them. Your help will be very welcome. 

Sorry but I have to close this to cleanup the issues a little bit.
