### ISSUE TITLE
picked date not being inserted into input field on selected chrome browsers

### ISSUE THREAD

**Issue by arkid** [Pikaday/Pikaday#579]
Pikaday has suddenly stopped working for me on selected chrome browsers.      The pikaday calender renders fine but when you select a date it doesn't appear in the input box.

Whats odd is that the different computers that it works / doesn't work on are using exactly the same chrome build.   The regional settings are a little different on the systems but that's about the only difference I can determine.

The issue can be seen on the date pickers on our site homepage: http://www.apartmentnetwork.co.uk/

**Comment by patrick-collins-429** [comment]
I am having this bug as well

**Comment by patrick-collins-429** [comment]
Okay turns out it might be a css issue that is making the text color for your input box the same as the background. try setting it to a contrasting color and seeing if it shows now

**Comment by wojciechczerniak** [comment]
Too little details and I can't replicate the issue. Please provide steps to replicate then reopen.
