### ISSUE TITLE
Scroll on touch closes datepicker

### ISSUE THREAD

**Issue by linnett** [Pikaday/Pikaday#584]
If I open the datepicker on a touch device and then try and scroll over the calendar, it selects the date rather than allowing the scroll. I would expect the date to be selected on click but when the user is scrolling over the datepicker, it should not disappear.

**Comment by wojciechczerniak** [comment]
Linked PR #397

**Comment by wojciechczerniak** [comment]
Actually this is a duplicate of  #569
