### ISSUE TITLE
Use dates array instead of minDate and maxDate to restrict date picking

### ISSUE THREAD

**Issue by isvaljek** [Pikaday/Pikaday#589]
Is there a way to init Pikaday with an date array [ date1, date2, date3 ... ] to restrict date picking to just those dates?
A client has a locations and classes objects, and classes can have different dates, which can be chosen in the admin afterwards (hopefully).

**Comment by isvaljek** [comment]
Created a pull request that adds this functionality.

**Comment by wojciechczerniak** [comment]
There is an `disableDayFn` option now.
