### ISSUE TITLE
Is it possible to set different formats?

### ISSUE THREAD

**Issue by ersanceylan** [Pikaday/Pikaday#591]
I wonder if it is possible to set different formats for shown value and posted value without manipulating form submit event.

For example;
I want users to see datepicker format as `MMM dd, YYYY`
but I also sent date input formatted as `YYYY-MM-DD`

**Comment by trodicaro** [comment]
We are using Pikaday at my job and we'd benefit from a similar formatting (in our case render on page American date and send behind the scenes as ISO 8601: render 01/09/2017 vs send 2017/01/09.

**Comment by dave1010** [comment]
Dupe of #452 ?

**Comment by wojciechczerniak** [comment]
Duplicate of #452. Thanks @dave1010
