### ISSUE TITLE
Loading typings from moment in node_modules

### ISSUE THREAD

**Issue by maxmumford** [Pikaday/Pikaday#593]
Hi all,

I'm using pikaday inside an angular2 app with webpack. The pikaday typings try to load moment's typings definition file from within the typings folder. However I want to load the typings included in node_modules/moment at moment.d.ts.

I've created my own pikaday.d.ts file based on the one here:

https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/master/pikaday/pikaday.d.ts

and changed the moment reference line to:

`/// <reference path="../../../node_modules/moment/moment.d.ts" />`

but when compiling I get the error message Cannot find namespace 'moment'. VSCode however doesn't complain about the path. Any idea what's going wrong?

**Comment by rikkert** [comment]
Do you have a fix for this by now?

**Comment by maxmumford** [comment]
No fix yet, it's just a typescript warning and doesn't prevent transpile, but I do need to find a fix

**Comment by rikkert** [comment]
Should we just close this one then?

**Comment by maxmumford** [comment]
I'd prefer not. It's a problem other users have experienced, and something I do need to sort out, I just don't know how

**Comment by florianbepunkt** [comment]
+1

**Comment by idchlife** [comment]
Having similar issue with TypeScript:

 error TS2694: Namespace '".../node_modules/moment/moment".export=' has no exported member 'Moment'.

**Comment by wojciechczerniak** [comment]
Will no longer be an issue after #815
