### ISSUE TITLE
Issue with dynamic require() when using webpack

### ISSUE THREAD

**Issue by RobertMenke** [Pikaday/Pikaday#604]
Hey guys,

I want to bring up an issue I came across and solved to your attention. It looks like you're dynamically requiring moment.js on this line https://github.com/dbushell/Pikaday/blob/master/pikaday.js#L23 which causes webpack to try to require every single file from the pikaday path and produces errors.

The solution for anyone running into this problem is to use the `imports-loader` as follows:
```javascript
{
      test: /pikaday\.js$/,
      loader : 'imports?define=>false'
}
```

**Comment by ThomasLabstep** [comment]
Thanks for this fix.

Now what is the solution for webpack 4 ?

**Comment by wojciechczerniak** [comment]
Duplicate of #815
