### ISSUE TITLE
Status / still maintained?

### ISSUE THREAD

**Issue by dandv** [Pikaday/Pikaday#619]
I'm thinking of recommending pikaday to a large company, but wondering about the status of the project, given the relatively large number of PRs and issues, including simple ones like adding npm install instructions. Thanks!

**Comment by PhiLhoSoft** [comment]
Looking at https://github.com/dbushell/Pikaday/blob/master/CHANGELOG.md I see the last changes were made in October 2016, which is recent. Although previous changes were done a year before!
I guess it is a one-man project, done on free time, victim of its success, like so many...

**Comment by wojciechczerniak** [comment]
Yup, it's still maintained.
