### ISSUE TITLE
gotoDate() doesnt highlight day

### ISSUE THREAD

**Issue by El4a** [Pikaday/Pikaday#623]
Hi!

When I use the gotoDate() function, it displays the correct year and month when the datepicker is opened, but the day isn't highlighted in anyway. It would be nicer if the day also had the class 'is-selected'. Not sure if this is a bug or a feature :)

Here's my fiddle that illustrates the issue.

https://jsfiddle.net/El4a/eerxbzc2/

The pikaday code is tweaked a little bit, but I tested with the pure source code aswel and that has the same behavior.

Btw: love the lib :)

**Comment by chyingp** [comment]
@El4a You may try `setDate()`function, it will set the selected date and highlight it as well.

By the way, if you don't want the `onSelect` callback triggered, you may pass `false` as the second param.

```
setDate: function(date, preventOnSelect)
```

**Comment by wojciechczerniak** [comment]
`goToDate` will "Change the current view to see a specific date." as readme says. To actually select the date use `setDate` as @chyingp suggested. Closing this question as answered. Thanks @chyingp
