### ISSUE TITLE
getDate() behaviour is unexpected

### ISSUE THREAD

**Issue by koenhoeijmakers** [Pikaday/Pikaday#629]
The documentation states that `pikaday.getDate()` is supposed to return a basic JavaScript `Date` object of the selected day, or `null` if no selection.

Although the function declaration states:
```javascript
getDate: function()
{
    return isDate(this._d) ? new Date(this._d.getTime()) : new Date();
},
```

Which indicates that it returns a JavaScript `Date` object instead of `null` as stated in the documentation.

I for now didn't make a pull request since i don't know which one of these is the expected behaviour.

**Comment by alexbaulch** [comment]
+1 either the documentation or the code needs updating to match

**Comment by Frazer** [comment]
I think it should return null, otherwise, what way is there to know that no date has been chosen.

**Comment by wojciechczerniak** [comment]
It returns `null` now: https://github.com/Pikaday/Pikaday/blob/f95c640a46d490afe572895d4393d286faab8661/pikaday.js#L781
I can close this issue.
