### ISSUE TITLE
Changing the date with js doesn't change the selected date of datepicker

### ISSUE THREAD

**Issue by paran0a** [Pikaday/Pikaday#634]
Demo is simple, go to
[Demo](http://dbushell.github.io/Pikaday/)

And execute
document.getElementById('datepicker').value ='Fri Jan 29 2016';

When you open the datepicker the date won't be set to what the value of the field is.

What's the solution?

**Comment by elzix** [comment]
Hi, I'm having a similar problem.

I followed the issues from #61 >> #63 >> #76 >> #51 but nothing has been said about the fix on minDate during runtime.

I have the following code:
```
<script type="text/javascript">
jQuery( document ).ready( function( $ ) {
  $(document.body).find( '#date1' ).pikaday( { minDate: new Date( ) } ); // date1 is today's date (works)
  $(document.body).find( '#date2' ).pikaday( { minDate: new Date( ) } ); // date2 is today's date (works)

  $('#date1').on('change',function(){ // when date1 changes
    // Get and format date
    date = new Date(jQuery('#date1').val());
    var dd=date.getDate()+1;
    var mm=date.getMonth()+1;
    var yyyy=date.getFullYear();
    if(dd<10)dd='0'+dd;
    if(mm<10)mm='0'+mm;
    date=yyyy+'-'+mm+'-'+dd; alert(date); // Gives somthing similar to '2017-01-23'  (works)
    $(document.body).find( '#date2' ).pikaday( { minDate: new Date( date ) } ); // date2 is date1's date +1 (does not work) [no error] 
    $(document.body).find( '#date2' ).setMinDate( date ); // date2 is date1's date +1 (does not work) [setMinDate is not a function]
    } );
} );
</script>
```

Is the only solution [MoOx's fix from 2013](https://github.com/dbushell/Pikaday/pull/63#commitcomment-3177759), is there another release coming, or is there something I am doing wrong?

**Comment by CPritch** [comment]
I'm so sorry I only discovered this now, been doing a lot of client work with this date picker.

Haven't tested but should work fine with this code:

`document.getElementById('datepicker').value = 'Fri Jan 29 2016'
document.getElementById('datepicker').dispatchEvent(new Event('input'));`

**Comment by BrandoIsNotASword** [comment]
Any follow up on this? Tried @CPritch's solution but it doesn't work apparently.

**Comment by elalemanyo** [comment]
It is also not working for me. I did a small [test](https://codepen.io/elalemanyo/pen/PyWobV) if anyone want to test and maybe help.

**Comment by wojciechczerniak** [comment]
Thanks @elalemanyo! Please use the `setDate` method. Solved.
