### ISSUE TITLE
Moment.js as a non-optional dependency?

### ISSUE THREAD

**Issue by andypanix** [Pikaday/Pikaday#648]
I'm relative new to the `node.js` world so maybe this is a silly question, but why when I add pikaday to my node project, `moment.js` is downloaded and setted as a dependency (in `node_modules/pikaday/package.json`), even if it should be an optional depencendy (I don't need/want moment.js in my project).

I've configured my app `package.json` to clone latest commit from Github repo:

`"pikaday": "git@github.com:dbushell/Pikaday.git#e2defb22cd78da263dace78445eb01af76ff0258"`

but when looking in `node_modules/pikaday/package.json` i see:

```
  "dependencies": {
    "moment": "2.x"
  },
```
and some lines below:

```
  "optionalDependencies": {
    "moment": "2.x"
  },
```

I'm missing something?

Thanks!
Andrea

**Comment by JulesAlexiu** [comment]
Hello,

I'm having the same issue.
If I don't install moment via npm, I have the following error `root is undefined` in the console.

Any ideas ?
Thanks for any piece of  advice !

**Comment by wojciechczerniak** [comment]
Moment was removed from package.json completely in 1.8.0 release.
