### ISSUE TITLE
IE 8 compatibility issue

### ISSUE THREAD

**Issue by luis-andre** [Pikaday/Pikaday#649]
I think pikaday.js lost its compatibility with IE 7/8 after the insertion of line:

1087: hasEvent = opts.events.indexOf(day.toDateString()) !== -1 ? true : false,

...since Array.indexOf is not implement in those browsers.

**Comment by SMEmp** [comment]
[The polyfill on MDN][Polyfill] is rather small when minified, is that an option for you?

[Polyfill]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf#Polyfill

**Comment by wojciechczerniak** [comment]
Supported with polyfill. Thanks @ghost, I can close this issue.
