### ISSUE TITLE
Invalid argument on date select in IE8

### ISSUE THREAD

**Issue by kjf** [Pikaday/Pikaday#65]
With the following code:

``` javascript
$('li.more a').pikaday({
    minDate: new Date(),
    onSelect: function() {
        return console.log('Broken!');
    }
});
```

I receive an invalid arguement on line 70, i.e. here:

``` javascript
el.fireEvent('on' + eventName, ev);
```

Working fine in every other browser I've tested.

**Comment by catdad** [comment]
I faced this issue as well, and it is a really easy fix. I submitted a pull request here, and I hope that it can be merged soon.

https://github.com/dbushell/Pikaday/pull/316

**Comment by wojciechczerniak** [comment]
A lot of time has passed since this issue was created and we're going to drop support for older IE versions. Closing it.
