### ISSUE TITLE
Pick a day of prev or next months

### ISSUE THREAD

**Issue by GiacomoK** [Pikaday/Pikaday#652]
Hi,
is it possible to pick a day of pref or next months?

The "showDaysInNextAndPreviousMonths" config value affects just the visualization of the days, not the picking.

**Comment by braczek** [comment]
I've also needed this so i modified the library and added pull request.
If you still need this check out PR
https://github.com/dbushell/Pikaday/pull/674

**Comment by wojciechczerniak** [comment]
Merged in #674
