### ISSUE TITLE
Date format problem when i18n config is present

### ISSUE THREAD

**Issue by sosoxuc** [Pikaday/Pikaday#656]
I provide i18n config and calendar is perfect, But when i choose date, field value is set to standard formating "Fri Mar 03 2017" not  "პარ მარ 03 2017". How to fix this ?

**Comment by sosoxuc** [comment]
As I can see it uses standard js toDateString, needs moment as it seems :smile:

**Comment by spicalous** [comment]
@sosoxuc Should close this issue if it has been resolved :)
