### ISSUE TITLE
New release for events

### ISSUE THREAD

**Issue by joshsmith** [Pikaday/Pikaday#661]
Thanks for all the hard work on this library!

Is it possible to publish a new release to `npm` to bring in the `events` optionality documented in the `README`?

Thanks!

**Comment by hundekoerper** [comment]
as a workaround until the npm package is updated you can use the git repo as a dependency:

  `"dependencies": {
    "pikaday": "git@github.com:dbushell/Pikaday.git"
  }`

**Comment by wojciechczerniak** [comment]
I think that the changes you mentioned were released in v1.6.0.
