### ISSUE TITLE
Input field shows English date instead of internationlization

### ISSUE THREAD

**Issue by q2apro** [Pikaday/Pikaday#667]
For example here: http://dio-el-claire.github.io/PikadayTime/

Russian i18n shows up when clicking the input field, after choosing a date it appears as English version in the input field.

How to get the localisation also into the input field?

**Comment by thelambofgoat** [comment]
You can do this, though it's not obvious. Yes, Pikaday don't use internationalization data when filling input field. But if you look at the code you see that if **moment** object exists Pikaday uses _moment.js_ to fill input field, and if _moment.js_ has Russian locale, so it will be filled with Russian i18n.

**Comment by wojciechczerniak** [comment]
Or you can use `toString` option to customize the value however you want. Closing as answered. Thanks @thelambofgoat
