### ISSUE TITLE
Permission on forking and rebranding as Pikarange

### ISSUE THREAD

**Issue by willypt** [Pikaday/Pikaday#668]
Hello @dbushell, I've created a pull request and upon further development, I see that the "usage" of the product has gone different than yours.
Therefore, I decided to fork and re-publish the plugin I'm working on as [Pikarange](https://github.com/willypt/Pikarange).

Thanks a lot for the plugin! This by far is the simplest datepicker I've been using. Kudos to you and contributors!

**Comment by wojciechczerniak** [comment]
Yeah, sure. It's MIT. Your plugins is great too!
