### ISSUE TITLE
Requiring moment.js in a try/catch leads to unintended consequences.

### ISSUE THREAD

**Issue by emilbjorklund** [Pikaday/Pikaday#722]
I know there are a few different issues related to the "optional" nature of Moment.js in this library.
Addressing the presence of `moment` in the `dependencies` of `package.json` (e.g [this pull request](https://github.com/dbushell/Pikaday/pull/721/commits/659c10bc53ec48edb17b467cab6464a5cd0e4e1f)) is a start, but not enought, in my opinion.

The mechanism of using a try/catch is a bit too coarse, as it will include `moment` in the bundle, just based on what’s installed locally – not whether the author wants to include it in the client-side bundle.

Example: since I use `moment` in my build chain (gulp etc), it is available via `require`, but that doesn't mean I want to use it with Pikaday. I can ignore it via the bundler toolchain, but it seems like the API could be updated in a future release to accept a `moment` instance as part of the passed-in options instead.

**Comment by solotoo** [comment]
version 1.61 is still the latest version currently available from npm. so moment.js still being imported, and now being flagged as vulnerable by `nsp check`

**Comment by wojciechczerniak** [comment]
Duplicate of #815
