### ISSUE TITLE
custom toString() documentation incorrect

### ISSUE THREAD

**Issue by TennisVisuals** [Pikaday/Pikaday#733]
providing custom toString() function doesn't work as described.

**Comment by zaygraveyard** [comment]
In what way?
Can you give an example?

**Comment by TennisVisuals** [comment]
sorry for the delay in response... I was unable to implement a custom toString() function, and when I dug into the code to do some debugging it seemed to me that custom toString() functions are not actually supported, but I could be wrong.  I have moved on and handled my requirements in a different way... sorry not to be more specific!  The library is great. Thank you.

**Comment by zaygraveyard** [comment]
First of, I want to thank the author (and all the contributors) for this awesome library.
Second, customizing `toString()` can be done in the options see [Formatting](https://github.com/dbushell/Pikaday#formatting) section of the README.

Although the `toString` option doesn't replace the real `toString` of the `Pikaday` instance, the only difference is that `options.toString()` doesn't get the chance to format invalid dates (which always get formatted as `''`).

Anyway thank you for sharing 😄

**Comment by wojciechczerniak** [comment]
Thanks @zaygraveyard for the great answer. I can close this now.
