### ISSUE TITLE
Enabled dates when maxDate < minDate

### ISSUE THREAD

**Issue by lusarz** [Pikaday/Pikaday#737]
I noticed here:
https://github.com/dbushell/Pikaday/blob/master/pikaday.js#L716-L718

that all dates becomes enabled when maxDate < minDate. We have scenario in our application, where we want all dates to become disabled in this case. It seems to be more natural behavior.

**Comment by wojciechczerniak** [comment]
I can't agree with that. If `maxDate` is lower than `minDate` then we have invalid settings. You can handle this scenario on your side. Check the `maxDate` and `minDate` values you are providing to the Pikaday and adjust them to your liking or you can disable Pikaday at all.
