### ISSUE TITLE
mindate a month in the future

### ISSUE THREAD

**Issue by flexrumblecrunch** [Pikaday/Pikaday#743]
Is there a way to make the mindate a month in the future always stay that way?

**Comment by wojciechczerniak** [comment]
You can calculate Date.now + 1 month as the Date object that you use to setup `minDate`.

**Comment by chrisvidal** [comment]
I tried this 
```js
minDate: function() {
            var d = new Date();
            d.setMonth(d.getMonth() + 3);
            return d;
            },
```

but it does not work, any idea why?
