### ISSUE TITLE
Time entry only

### ISSUE THREAD

**Issue by weedkiller** [Pikaday/Pikaday#754]
Hi, I have user who just want to enter amount of time worked, i.e. how long and not when.

I was unable to disable the AM & PM text, can you please share the setting/example to disable it.

Also 

- [ ] how to show default hours: for e.g. on select box, `default to 08:00 hrs.`
- [ ] Different color for hours (Blue) and Mins (green)
- [ ] show a button to fill `https://github.com/kbwood/timeentry/blob/master/jquery.timeentry.js`
![image](https://user-images.githubusercontent.com/21086190/34395645-00141932-eb30-11e7-9288-dc1586832120.png)

thanks

**Comment by wojciechczerniak** [comment]
Pikaday doesn't have time picker functionality. You are referring to some other plugin?
