### ISSUE TITLE
The month is remembered upon each opening

### ISSUE THREAD

**Issue by bigdatagithub** [Pikaday/Pikaday#759]
Hi, 

Each time I re-open the same Calendar popup, it remembers the month in my last opening. 

Can we tweak this behavior? Like, it always defaults to current month upon each opening. 

Thanks a lot!

**Comment by psalaets** [comment]
Use the `onOpen` option to reset the picker how you want it.

**Comment by wojciechczerniak** [comment]
Question answered. Thanks @psalaets
