### ISSUE TITLE
missing release / tag on GitHub

### ISSUE THREAD

**Issue by DanielRuf** [Pikaday/Pikaday#771]
npm lists 1.7.0 but this is not released here.

**Comment by kondi** [comment]
Even the package.json says it is 1.6.1 :(

**Comment by tanishiking** [comment]
@rikkert Pikaday seems not have released changes after [this commit](https://github.com/dbushell/Pikaday/commit/2216628502e986368362af7420f9afee9cc30d1c#diff-5e6a2e8d597bd0e8a3111ba17c4a0815).
Would you please release latest changes as 1.7.0 to npm and github?
(I want to use [this feature](https://github.com/dbushell/Pikaday/commit/6d04f79ace06890e07a8b43d86ebacad183eac9e) which is not yet released.)

**Comment by wojciechczerniak** [comment]
1.7.0 is now tagged and added to releases.
