### ISSUE TITLE
npm distribution - moment js is in resulting bundle

### ISSUE THREAD

**Issue by MarcelGeo** [Pikaday/Pikaday#789]
package.json configuration of pikaday is installing moment.js as dependency. Moment.js is large sized library, and therefore we dont wanna moment by default. 

Is it possible to remove moment from dependencies?

**Comment by siddarthvader** [comment]
Facing the same issue, although the size of pikaday lib is around 40kb, including moment js adds almost 500kb ro my built, i dont want that load on my code. Kindly provide a way to get out of this. Thanks.

**Comment by siddarthvader** [comment]
So I was using webpack and this helped a great deal https://github.com/dbushell/Pikaday/issues/718

**Comment by wojciechczerniak** [comment]
Moment was removed from dependencies in 1.8.0 release.
