### ISSUE TITLE
Year and month Select isn't clear to select by user

### ISSUE THREAD

**Issue by pnxtm** [Pikaday/Pikaday#792]
Hi,
I have noticed that end users don't understand the existence of ability to select years and months directly, and try to reach their wanted date by using the arrows. If there is any idea how to help them, please help me to implement that too.

Thanks a lot to this awesome date picker.
Best regards.

**Comment by garimasingh18** [comment]
Hi,

I have similar concern. Is it possible to access Month and Year dropbox using Keyborad?

Thanks!

**Comment by MeigaraJuma** [comment]
Hello,

I really need to know too, how to get a date, months and years value for each dropdown input?


Thx

**Comment by pnxtm** [comment]
Thanks @psalaets, great idea, It's very better now.

**Comment by wojciechczerniak** [comment]
Thanks @psalaets for answering this issue. I can close it now.

PR with alternative themes are welcome.
