### ISSUE TITLE
Release with latest changes (the removal of momemt.js as dependency)

### ISSUE THREAD

**Issue by PikachuEXE** [Pikaday/Pikaday#805]
#721 is merged but seems not released

Also very strange to see that `1.7.0` tag is absent

**Comment by nathanchase** [comment]
Yes, we need a fully "Moment-less" Pikaday - or at the very least, use [moment-mini](https://github.com/ksloan/moment-mini) so that Moment's usage is minimized to the necessary elements.

**Comment by wojciechczerniak** [comment]
Tag for 1.7.0 was added and newer version was released.

**Comment by PikachuEXE** [comment]
Ya I noticed that and switched to `1.8.0` already
Thanks for the release :)
