### ISSUE TITLE
Can't format datepicker result

### ISSUE THREAD

**Issue by Delifisek** [Pikaday/Pikaday#823]
Some how I can't format pikaday result. Moment js or not

    var picker = new Pikaday(
    {
        field: document.getElementById('datepicker'),
        format : "MM/DD/YYYY",
        firstDay: 1,
        minDate: new Date('2000-01-01'),
        maxDate: new Date(),
        yearRange: [2000,2020]      
    });

This thing work on  here
http://jsfiddle.net/janfoeh/t046bqm2/3/

copy pasting same code on my code results 
Fri Dec 07 2018 
I'm after 07/12/2018

I try every google/stackoverflow solution and I can't get any results.

Is there something missing ? or what ?

My best regards

**Comment by Delifisek** [comment]
var picker = new Pikaday({
                field: document.getElementById("birth_date"),
                format: "D/M/YYYY",
                toString(date, format) {
                    const day = date.getDate();
                    const month = date.getMonth() + 1;
                    const year = date.getFullYear();
                    return `${day}/${month}/${year}`;
                },
                parse(dateString, format) {
                    // dateString is the result of `toString` method
                    const parts = dateString.split('/');
                    const day = parseInt(parts[0], 10);
                    const month = parseInt(parts[1], 10) - 1;
                    const year = parseInt(parts[2], 10);
                    return new Date(year, month, day);
                }
            });

This was fix the problem.

**Comment by wojciechczerniak** [comment]
Solved.
