### ISSUE TITLE
showWeekNumber does not show the correct week numbers

### ISSUE THREAD

**Issue by kvdheuvel** [Pikaday/Pikaday#878]
## Bug report
The week numbers for the year 2021 does not show the correct numbers. In 2021 the first week should be starting at 04-01-2021 and right now it starts at 01-01-2021.

### Steps to reproduce
1. Open the datepicker with the option showWeekNumber set to true
2. Select the year 2021 
3. Select the first month
4. Week 1 is shown at 01-01-2021 / 03-01-2021

### Actual behavior
Week 1 starts at the first day of the year

### Expected behavior
Week 1 should start at the first week mentioned by ISO (04-01-2021)

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| Browser          | Chrome
| Operating System | Windows 10

**Comment by kvdheuvel** [comment]
@wojciechczerniak I just noticed you completed a pull-request regarding this issue. Do you know if this fix will be released soon?

**Comment by jvalst** [comment]
I guess it's a leap year thing.. Should be very nice if this gets released. Is there a possibility to override the renderWeek() function? So we could fix it temporarily inside our own code? Don't want to mess inside the node_modules. Thanks for the help.

**Comment by jvalst** [comment]
Ok, checked the current sources on github. The Leap year thing is fixed already, but not published yet... Can @rikkert publish it as "beta" maybe on npm?

**Comment by aggerbo** [comment]
Still no solution to this issue?

**Comment by Bafan** [comment]
As I found, there is already a [fix ](https://github.com/Pikaday/Pikaday/commit/5c1a7559be0373c93f971366abd6ddff82b18ed0)for this issue in the master branch but haven't released yet. Is there any plan to release a new version including that fix?

**Comment by dannyfranken-coolblue** [comment]
@dbushell or @rikkert can you please consider to release a new version with the ISO week fix? All the week numbers for 2021 are incorrect (actual week number +1).

**Comment by rikkert** [comment]
You are right guys, fix is released with 1.8.2.
