### ISSUE TITLE
Grunt uglification fails

### ISSUE THREAD

**Issue by flo-rider** [Pikaday/Pikaday#890]
I have this code:

	`var picker = new Pikaday(
	{
		field: document.getElementById('CPH_Main_tbReservationDate'),
		firstDay: 1,
		keyboardInput: false,
		minDate: new Date(),
		format: 'ignorednow',
		toString(date, format) {
			// you should do formatting based on the passed format,
			// but we will just return 'D/M/YYYY' for simplicity
			var day = date.getDate();
			var month = date.getMonth() + 1;
			var year = date.getFullYear();

			if (day.toString().length == 1) { day = '0' + day; }
			if (month.toString().length == 1) { month = '0' + month; }

			if (lang == 'en') {
				return `${month}/${day}/${year}`;
			}
			else {
				return `${day}-${month}-${year}`;
			}

		}
	});`
    
However, when I try to uglifyit using grunt uglify, it throws an error:

Warning: Uglification failed. Unexpected token punc «(», expected punc «:». Line 103 in js/test.js Use --force to continue.

It expects a : after toString (on this line toString(date, format)), however, that is the actual needed code. How can I fix this?

**Comment by rikkert** [comment]
I think you have to add the colon and a fat arrow function:

`var picker = new Pikaday(
{
	field: document.getElementById('CPH_Main_tbReservationDate'),
	firstDay: 1,
	keyboardInput: false,
	minDate: new Date(),
	format: 'ignorednow',
	toString: (date, format) => {
		// you should do formatting based on the passed format,
		// but we will just return 'D/M/YYYY' for simplicity
		var day = date.getDate();
		var month = date.getMonth() + 1;
		var year = date.getFullYear();

		if (day.toString().length == 1) { day = '0' + day; }
		if (month.toString().length == 1) { month = '0' + month; }

		if (lang == 'en') {
			return `${month}/${day}/${year}`;
		}
		else {
			return `${day}-${month}-${year}`;
		}

	}
});`
